// <auto-generated />
using System;
using HRManagementSystem;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRManagementSystem.Migrations
{
    [DbContext(typeof(HRMSDbContext))]
    [Migration("20260314221708_ChangeNameMaxLengthInPayableBenefitsTable")]
    partial class ChangeNameMaxLengthInPayableBenefitsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRManagementSystem.Models.ApprovedOvertime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("ApprovedOn")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("HoursAllowed")
                        .HasColumnType("tinyint");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.ToTable("ApprovedOvertimes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Bonus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountOrPercent")
                        .HasColumnType("decimal(9,2)");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("HRManagementSystem.Models.BusinessLocation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("StateId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("BusinessLocations");
                });

            modelBuilder.Entity("HRManagementSystem.Models.CompanyInfo", b =>
                {
                    b.Property<short>("BusinessLocationId")
                        .HasColumnType("smallint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasIndex("BusinessLocationId");

                    b.ToTable("CompanyInfo");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Deduction", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsPreTax")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Deductions");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Department", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRManagementSystem.Models.DepartmentBonus", b =>
                {
                    b.Property<byte>("DepartmentId")
                        .HasColumnType("tinyint");

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<bool>("WasPaid")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId", "BonusId");

                    b.HasIndex("BonusId");

                    b.ToTable("DepartmentBonuses");
                });

            modelBuilder.Entity("HRManagementSystem.Models.DirectDepositInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("AccountNumberHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte>("FinancialInstitutionId")
                        .HasColumnType("tinyint");

                    b.Property<int>("PayrollInfoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FinancialInstitutionId");

                    b.HasIndex("PayrollInfoId");

                    b.ToTable("DirectDepositInfos");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("char(10)");

                    b.Property<byte>("StateId")
                        .HasColumnType("tinyint");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("char(5)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeAccruedTimeOff", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("TimeOffTypeId")
                        .HasColumnType("tinyint");

                    b.Property<short>("AccruedHours")
                        .HasColumnType("smallint");

                    b.Property<byte>("AccruedMinutes")
                        .HasColumnType("tinyint");

                    b.HasKey("EmployeeId", "TimeOffTypeId");

                    b.HasIndex("TimeOffTypeId");

                    b.ToTable("EmployeeAccruedTimeOffs");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeBonus", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("BonusId")
                        .HasColumnType("int");

                    b.Property<bool>("WasPaid")
                        .HasColumnType("bit");

                    b.HasKey("EmployeeId", "BonusId");

                    b.HasIndex("BonusId");

                    b.ToTable("EmployeeBonuses");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeContributableAccount", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("PayableBenefitId")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("AccountNumberHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<decimal>("EmployeeContribution")
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("EmployeeContributionIsPercent")
                        .HasColumnType("bit");

                    b.Property<decimal>("EmployeeYearlyMaxAllowed")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("EmployeeId", "PayableBenefitId");

                    b.HasIndex("PayableBenefitId");

                    b.ToTable("EmployeeContributableAccounts");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeDeclinedPayableBenefit", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("PayableBenefitId")
                        .HasColumnType("tinyint");

                    b.HasKey("EmployeeId", "PayableBenefitId");

                    b.HasIndex("PayableBenefitId");

                    b.ToTable("EmployeeDeclinedPayableBenefits");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeDeduction", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("DeductionId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsPercent")
                        .HasColumnType("bit");

                    b.Property<decimal>("RateOrAmount")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("EmployeeId", "DeductionId");

                    b.HasIndex("DeductionId");

                    b.ToTable("EmployeeDeductions");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeInsurancePlan", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<short>("InsurancePlanId")
                        .HasColumnType("smallint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyCharges")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("EmployeeId", "InsurancePlanId");

                    b.HasIndex("InsurancePlanId");

                    b.ToTable("EmployeeInsurancePlans");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeJobTitle", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<short>("JobTitleId")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("EmployeeId", "JobTitleId");

                    b.HasIndex("JobTitleId");

                    b.ToTable("EmployeeJobTitle");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeePicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeePictures");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("BeginTime")
                        .HasColumnType("time");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<short>("MinutesLate")
                        .HasColumnType("smallint");

                    b.Property<short>("MinutesLeftEarly")
                        .HasColumnType("smallint");

                    b.Property<bool>("MissedShift")
                        .HasColumnType("bit");

                    b.Property<short>("WorkDayId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("WorkDayId");

                    b.ToTable("EmployeeShifts");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeTimeOffUse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte>("Hoursused")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MinutesUsed")
                        .HasColumnType("tinyint");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("TimeOffTypeId")
                        .HasColumnType("tinyint");

                    b.Property<short>("WorkDayId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TimeOffTypeId");

                    b.HasIndex("WorkDayId");

                    b.ToTable("EmployeeTimeOffUses");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeTypes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmploymentPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("BusinessLocationId")
                        .HasColumnType("smallint");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("LastDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BusinessLocationId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmploymentPeriods");
                });

            modelBuilder.Entity("HRManagementSystem.Models.FederalTax", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("Id");

                    b.ToTable("FederalTaxes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.FinancialInstitution", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("char(9)");

                    b.HasKey("Id");

                    b.ToTable("FinancialInstitutions");
                });

            modelBuilder.Entity("HRManagementSystem.Models.FixedSchedule", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<bool>("WorkOnFriday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnMonday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnSaturday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnSunday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnThursday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnTuesday")
                        .HasColumnType("bit");

                    b.Property<bool>("WorkOnWednesday")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FixedSchedules");
                });

            modelBuilder.Entity("HRManagementSystem.Models.FixedScheduleEmployee", b =>
                {
                    b.Property<byte>("FixedScheduleId")
                        .HasColumnType("tinyint");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("FixedScheduleId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("FixedScheduleEmployees");
                });

            modelBuilder.Entity("HRManagementSystem.Models.InsuranceCompany", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("InsuranceCompanies");
                });

            modelBuilder.Entity("HRManagementSystem.Models.InsurancePlan", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<byte>("InsuranceCompanyId")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<byte>("PayableBenefitId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceCompanyId");

                    b.HasIndex("PayableBenefitId");

                    b.ToTable("InsurancePlans");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitle", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<byte>("DepartmentId")
                        .HasColumnType("tinyint");

                    b.Property<byte>("EmployeeTypeId")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsFixedSchedule")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullTime")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOvertimeExempt")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("PaymentPeriodTypeId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.HasIndex("PaymentPeriodTypeId");

                    b.ToTable("JobTitles");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitlePayableBenefit", b =>
                {
                    b.Property<short>("JobTitleId")
                        .HasColumnType("smallint");

                    b.Property<byte>("PayableBenefitId")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("EmployerContribution")
                        .HasColumnType("decimal(7,2)");

                    b.Property<bool>("EmployerContributionIsPercent")
                        .HasColumnType("bit");

                    b.Property<decimal>("EmployerYearlyMaxAllowed")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("JobTitleId", "PayableBenefitId");

                    b.HasIndex("PayableBenefitId");

                    b.ToTable("JobTitlePayableBenefits");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitleTimeOffType", b =>
                {
                    b.Property<short>("JobTitleId")
                        .HasColumnType("smallint");

                    b.Property<byte>("TimeOffTypeId")
                        .HasColumnType("tinyint");

                    b.Property<short>("MaxHours")
                        .HasColumnType("smallint");

                    b.Property<short>("MaxYearlyCarryover")
                        .HasColumnType("smallint");

                    b.Property<bool>("PayOnTermination")
                        .HasColumnType("bit");

                    b.Property<bool>("PayOnUse")
                        .HasColumnType("bit");

                    b.Property<byte>("WorkHoursToOneHourOff")
                        .HasColumnType("tinyint");

                    b.HasKey("JobTitleId", "TimeOffTypeId");

                    b.HasIndex("TimeOffTypeId");

                    b.ToTable("JobTitleTimeOffTypes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.LocalTax", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHeadTax")
                        .HasColumnType("bit");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RateOrAmount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<byte>("StateId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("LocalTaxes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.PayableBenefit", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsInsurance")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("PayableBenefits");
                });

            modelBuilder.Entity("HRManagementSystem.Models.PaymentPeriodType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PaymentPeriodTypes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.PayrollInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<double>("FederalTaxWithholdingRate")
                        .HasColumnType("float");

                    b.Property<byte[]>("SSNHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<double>("StateTaxWithholdingRate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PayrollInfos");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Salary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHourly")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Salaries");
                });

            modelBuilder.Entity("HRManagementSystem.Models.State", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("HRManagementSystem.Models.StateTax", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(4,2)");

                    b.Property<byte>("StateId")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("StatesTaxes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.TimeOffType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsAccruable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TimeOffTypes");
                });

            modelBuilder.Entity("HRManagementSystem.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HRManagementSystem.Models.WorkDay", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("WorkDays");
                });

            modelBuilder.Entity("HRManagementSystem.Models.ApprovedOvertime", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HRManagementSystem.Models.BusinessLocation", b =>
                {
                    b.HasOne("HRManagementSystem.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRManagementSystem.Models.CompanyInfo", b =>
                {
                    b.HasOne("HRManagementSystem.Models.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessLocation");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Department", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HRManagementSystem.Models.DepartmentBonus", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Bonus", "Bonus")
                        .WithMany()
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("HRManagementSystem.Models.DirectDepositInfo", b =>
                {
                    b.HasOne("HRManagementSystem.Models.FinancialInstitution", "FinancialInstitution")
                        .WithMany()
                        .HasForeignKey("FinancialInstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PayrollInfo", "PayrollInfo")
                        .WithMany()
                        .HasForeignKey("PayrollInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialInstitution");

                    b.Navigation("PayrollInfo");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("HRManagementSystem.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeAccruedTimeOff", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.TimeOffType", "TimeOffType")
                        .WithMany()
                        .HasForeignKey("TimeOffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TimeOffType");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeBonus", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Bonus", "Bonus")
                        .WithMany()
                        .HasForeignKey("BonusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonus");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeContributableAccount", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PayableBenefit", "PayableBenefit")
                        .WithMany()
                        .HasForeignKey("PayableBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayableBenefit");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeDeclinedPayableBenefit", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PayableBenefit", "PayableBenefit")
                        .WithMany()
                        .HasForeignKey("PayableBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("PayableBenefit");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeDeduction", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Deduction", "Deduction")
                        .WithMany()
                        .HasForeignKey("DeductionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deduction");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeInsurancePlan", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.InsurancePlan", "InsurancePlan")
                        .WithMany()
                        .HasForeignKey("InsurancePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("InsurancePlan");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeJobTitle", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeePicture", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeShift", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.WorkDay", "WorkDay")
                        .WithMany()
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmployeeTimeOffUse", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.TimeOffType", "TimeOffType")
                        .WithMany()
                        .HasForeignKey("TimeOffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.WorkDay", "WorkDay")
                        .WithMany()
                        .HasForeignKey("WorkDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("TimeOffType");

                    b.Navigation("WorkDay");
                });

            modelBuilder.Entity("HRManagementSystem.Models.EmploymentPeriod", b =>
                {
                    b.HasOne("HRManagementSystem.Models.BusinessLocation", "BusinessLocation")
                        .WithMany()
                        .HasForeignKey("BusinessLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessLocation");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.FixedScheduleEmployee", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.FixedSchedule", "FixedSchedule")
                        .WithMany()
                        .HasForeignKey("FixedScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("FixedSchedule");
                });

            modelBuilder.Entity("HRManagementSystem.Models.InsurancePlan", b =>
                {
                    b.HasOne("HRManagementSystem.Models.InsuranceCompany", "InsuranceCompany")
                        .WithMany()
                        .HasForeignKey("InsuranceCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PayableBenefit", "PayableBenefit")
                        .WithMany()
                        .HasForeignKey("PayableBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InsuranceCompany");

                    b.Navigation("PayableBenefit");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitle", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PaymentPeriodType", "PaymentPeriodType")
                        .WithMany()
                        .HasForeignKey("PaymentPeriodTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EmployeeType");

                    b.Navigation("PaymentPeriodType");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitlePayableBenefit", b =>
                {
                    b.HasOne("HRManagementSystem.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.PayableBenefit", "PayableBenefit")
                        .WithMany()
                        .HasForeignKey("PayableBenefitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");

                    b.Navigation("PayableBenefit");
                });

            modelBuilder.Entity("HRManagementSystem.Models.JobTitleTimeOffType", b =>
                {
                    b.HasOne("HRManagementSystem.Models.JobTitle", "JobTitle")
                        .WithMany()
                        .HasForeignKey("JobTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRManagementSystem.Models.TimeOffType", "TimeOff")
                        .WithMany()
                        .HasForeignKey("TimeOffTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTitle");

                    b.Navigation("TimeOff");
                });

            modelBuilder.Entity("HRManagementSystem.Models.LocalTax", b =>
                {
                    b.HasOne("HRManagementSystem.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRManagementSystem.Models.PayrollInfo", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.Salary", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRManagementSystem.Models.StateTax", b =>
                {
                    b.HasOne("HRManagementSystem.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("HRManagementSystem.Models.User", b =>
                {
                    b.HasOne("HRManagementSystem.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
